# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ebpf_info.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ebpf_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65\x62pf_info.proto\x12\rmonitor.proto\"\'\n\x08PortStat\x12\x0c\n\x04port\x18\x01 \x01(\r\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"\x81\x02\n\x08\x45\x62pfInfo\x12\x19\n\x11\x65stablished_count\x18\x01 \x01(\x03\x12\x17\n\x0ftime_wait_count\x18\x02 \x01(\x03\x12\x18\n\x10\x63lose_wait_count\x18\x03 \x01(\x03\x12\x17\n\x0flistening_count\x18\x04 \x01(\x03\x12\x16\n\x0esyn_sent_count\x18\x05 \x01(\x03\x12\x16\n\x0e\x66in_wait_count\x18\x06 \x01(\x03\x12\x14\n\x0ctotal_active\x18\n \x01(\x03\x12\x1b\n\x13new_connection_rate\x18\x0b \x01(\x02\x12+\n\nport_stats\x18\x0c \x03(\x0b\x32\x17.monitor.proto.PortStatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ebpf_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PORTSTAT']._serialized_start=34
  _globals['_PORTSTAT']._serialized_end=73
  _globals['_EBPFINFO']._serialized_start=76
  _globals['_EBPFINFO']._serialized_end=333
# @@protoc_insertion_point(module_scope)
