# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import monitor_info_pb2 as monitor__info__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in monitor_info_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GrpcManagerStub(object):
    """gRPC服务定义
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SetMonitorInfo = channel.unary_unary(
                '/monitor.proto.GrpcManager/SetMonitorInfo',
                request_serializer=monitor__info__pb2.MonitorInfo.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMonitorInfo = channel.unary_unary(
                '/monitor.proto.GrpcManager/GetMonitorInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=monitor__info__pb2.MonitorInfo.FromString,
                _registered_method=True)
        self.GetAllMonitorInfo = channel.unary_unary(
                '/monitor.proto.GrpcManager/GetAllMonitorInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=monitor__info__pb2.AllMonitorInfo.FromString,
                _registered_method=True)


class GrpcManagerServicer(object):
    """gRPC服务定义
    """

    def SetMonitorInfo(self, request, context):
        """设置监控信息（客户端→服务器）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMonitorInfo(self, request, context):
        """获取监控信息（服务器→客户端）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllMonitorInfo(self, request, context):
        """获取所有主机的监控信息
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GrpcManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SetMonitorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMonitorInfo,
                    request_deserializer=monitor__info__pb2.MonitorInfo.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMonitorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMonitorInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=monitor__info__pb2.MonitorInfo.SerializeToString,
            ),
            'GetAllMonitorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllMonitorInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=monitor__info__pb2.AllMonitorInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'monitor.proto.GrpcManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('monitor.proto.GrpcManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GrpcManager(object):
    """gRPC服务定义
    """

    @staticmethod
    def SetMonitorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.proto.GrpcManager/SetMonitorInfo',
            monitor__info__pb2.MonitorInfo.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMonitorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.proto.GrpcManager/GetMonitorInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            monitor__info__pb2.MonitorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllMonitorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/monitor.proto.GrpcManager/GetAllMonitorInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            monitor__info__pb2.AllMonitorInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
